MONGODB_HOST: "mongodb.daws86s.store"
REDIS_HOST: "redis.daws86s.store"
CATALOGUE_HOST: "catalogue.daws86s.store"
CART_HOST: "cart.daws86s.store"
USER_HOST: "user.daws86s.store"
MYSQL_HOST: "mysql.daws86s.store"
RABBITMQ_HOST: "rabbitmq.daws86s.store"
SHIPPING_HOST: "shipping.daws86s.store"
PAYMENT_HOST: "payment.daws86s.store"