[mongodb]
localhost

[redis]
redis.daws86s.store

[mysql]
mysql.daws86s.store
# mysql.daws86s.store ansible_python_interpreter=/usr/bin/python3

[rabbitmq]
rabbitmq.daws86s.store

[catalogue]
catalogue.daws86s.store

[cart]
cart.daws86s.store

[user]
user.daws86s.store

[shipping]
shipping.daws86s.store

[payment]
payment.daws86s.store

[frontend]
frontend.daws86s.store

[local]
localhost

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

[local:vars]
NAME=from inventory
; COURSE=Ansible
; DURATION=07 days
; TRAINER=Siva kumar



